# Generated by Django 5.0.6 on 2024-07-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(
                choices=[
                    ("Ontario", "Ontario"),
                    ("Nova Scotia", "Nova Scotia"),
                    ("Alberta", "Alberta"),
                    ("British Columbia", "British Columbia"),
                    ("Quebec", "Quebec"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="zipcode",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("GC", "Green Compost"),
                    ("CB", "Green Carry Bag"),
                    ("RC", "Recycled Cloth"),
                    ("RB", "Recycled Bag"),
                    ("SP", "Solar PhoneCharger"),
                    ("GB", "Green Bag"),
                    ("UB", "Reusable Bottle"),
                    ("BC", "Reusable Bowl Cover"),
                ],
                max_length=2,
            ),
        ),
    ]
