# Generated by Django 5.0.6 on 2024-07-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_customer_state_alter_customer_zipcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("CR", "Curd"),
                    ("ML", "Milk"),
                    ("LS", "Lassi"),
                    ("MS", "Milkshake"),
                    ("PN", "Paneer"),
                    ("GH", "Ghee"),
                    ("CZ", "Cheese"),
                    ("IC", "Ice-Creams"),
                ],
                max_length=2,
            ),
        ),
    ]
