# Generated by Django 5.0.6 on 2024-07-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("GC", "Compost"),
                    ("ML", "Milk"),
                    ("LS", "Lassi"),
                    ("MS", "Milkshake"),
                    ("PN", "Paneer"),
                    ("GH", "Ghee"),
                    ("CZ", "Cheese"),
                    ("IC", "Ice-Creams"),
                ],
                max_length=2,
            ),
        ),
    ]
