# Generated by Django 5.0.6 on 2024-07-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("GC", "Compost"),
                    ("CB", "Bag"),
                    ("RC", "Cloth"),
                    ("SP", "Charger"),
                    ("UB", "Bottle"),
                    ("BC", "Cover"),
                    ("OT", "Other"),
                ],
                max_length=2,
            ),
        ),
    ]
